//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#if !EXCLUDE_CODEGEN
#pragma warning disable 162
#pragma warning disable 219
#pragma warning disable 693
#pragma warning disable 1591
#pragma warning disable 1998

namespace Orleans.StorageProvider.RavenDB.TestInterfaces
{
    using System;
    using System.Net;
    using System.Runtime.Serialization;
    using System.Runtime.Serialization.Formatters.Binary;
    using System.IO;
    using System.Collections.Generic;
    using System.Reflection;
    using Orleans.Serialization;
    using Orleans.StorageProvider.RavenDB.TestInterfaces;
    using Orleans;
    using Orleans.Runtime;
    using System.Collections;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class EmailFactory
    {
        

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail GetGrain(long primaryKey, string keyExt)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail), 938089621, primaryKey, keyExt));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail GetGrain(long primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail), 938089621, primaryKey, keyExt, grainClassNamePrefix));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail GetGrain(System.Guid primaryKey, string keyExt)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail), 938089621, primaryKey, keyExt));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail GetGrain(System.Guid primaryKey, string keyExt, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeKeyExtendedGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail), 938089621, primaryKey, keyExt,grainClassNamePrefix));
                        }

            public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return EmailReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
            "stInterfaces.IEmail")]
        internal class EmailReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail
        {
            

            public static Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail), (global::Orleans.Runtime.GrainReference gr) => { return new EmailReference(gr);}, grainRef, 938089621);
            }
            
            protected internal EmailReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal EmailReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 938089621;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
                        "stInterfaces.IEmail";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                EmailReference input = ((EmailReference)(original));
                return ((EmailReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                EmailReference input = ((EmailReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return EmailReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return EmailMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail.SetPerson(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson person)
            {

                return base.InvokeMethodAsync<object>(-646214881, new object[] {person is global::Orleans.Grain ? Orleans.StorageProvider.RavenDB.TestInterfaces.PersonFactory.Cast(person.AsReference()) : person} );
            }
            
            System.Threading.Tasks.Task<Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson> Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail.GetPerson()
            {

                return base.InvokeMethodAsync<Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson>(-1146556027, new object[] {} );
            }
            
            System.Threading.Tasks.Task Orleans.StorageProvider.RavenDB.TestInterfaces.IEmail.Send()
            {

                return base.InvokeMethodAsync<object>(-470441258, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
        "stInterfaces.IEmail", 938089621)]
    internal class EmailMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 938089621;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 938089621:  // IEmail
                        switch (methodId)
                        {
                            case -646214881: 
                                return ((IEmail)grain).SetPerson((IPerson)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case -1146556027: 
                                return ((IEmail)grain).GetPerson().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -470441258: 
                                return ((IEmail)grain).Send().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 938089621:  // IEmail
                    switch (methodId)
                    {
                        case -646214881:
                            return "SetPerson";
                    case -1146556027:
                            return "GetPerson";
                    case -470441258:
                            return "Send";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    public class PersonFactory
    {
        

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson GetGrain(long primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson), 438111581, primaryKey));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson GetGrain(long primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson), 438111581, primaryKey, grainClassNamePrefix));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson GetGrain(System.Guid primaryKey)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson), 438111581, primaryKey));
                        }

                        public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson GetGrain(System.Guid primaryKey, string grainClassNamePrefix)
                        {
                            return Cast(global::Orleans.CodeGeneration.GrainFactoryBase.MakeGrainReferenceInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson), 438111581, primaryKey, grainClassNamePrefix));
                        }

            public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return PersonReference.Cast(grainRef);
            }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
        [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
        [System.SerializableAttribute()]
        [global::Orleans.CodeGeneration.GrainReferenceAttribute("Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
            "stInterfaces.IPerson")]
        internal class PersonReference : global::Orleans.Runtime.GrainReference, global::Orleans.Runtime.IAddressable, Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson
        {
            

            public static Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson Cast(global::Orleans.Runtime.IAddressable grainRef)
            {
                
                return (Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson) global::Orleans.Runtime.GrainReference.CastInternal(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson), (global::Orleans.Runtime.GrainReference gr) => { return new PersonReference(gr);}, grainRef, 438111581);
            }
            
            protected internal PersonReference(global::Orleans.Runtime.GrainReference reference) : 
                    base(reference)
            {
            }
            
            protected internal PersonReference(SerializationInfo info, StreamingContext context) : 
                    base(info, context)
            {
            }
            
            protected override int InterfaceId
            {
                get
                {
                    return 438111581;
                }
            }
            
            protected override string InterfaceName
            {
                get
                {
                    return "Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
                        "stInterfaces.IPerson";
                }
            }
            
            [global::Orleans.CodeGeneration.CopierMethodAttribute()]
            public static object _Copier(object original)
            {
                PersonReference input = ((PersonReference)(original));
                return ((PersonReference)(global::Orleans.Runtime.GrainReference.CopyGrainReference(input)));
            }
            
            [global::Orleans.CodeGeneration.SerializerMethodAttribute()]
            public static void _Serializer(object original, global::Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
            {
                PersonReference input = ((PersonReference)(original));
                global::Orleans.Runtime.GrainReference.SerializeGrainReference(input, stream, expected);
            }
            
            [global::Orleans.CodeGeneration.DeserializerMethodAttribute()]
            public static object _Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
            {
                return PersonReference.Cast(((global::Orleans.Runtime.GrainReference)(global::Orleans.Runtime.GrainReference.DeserializeGrainReference(expected, stream))));
            }
            
            public override bool IsCompatible(int interfaceId)
            {
                return (interfaceId == this.InterfaceId);
            }
            
            protected override string GetMethodName(int interfaceId, int methodId)
            {
                return PersonMethodInvoker.GetMethodName(interfaceId, methodId);
            }
            
            System.Threading.Tasks.Task Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson.SetPersonalAttributes(Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes person)
            {

                return base.InvokeMethodAsync<object>(-1862634097, new object[] {person} );
            }
            
            System.Threading.Tasks.Task<string> Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson.GetFirstName()
            {

                return base.InvokeMethodAsync<System.String>(513673718, new object[] {} );
            }
            
            System.Threading.Tasks.Task<string> Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson.GetLastName()
            {

                return base.InvokeMethodAsync<System.String>(160660420, new object[] {} );
            }
            
            System.Threading.Tasks.Task<int> Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson.GetAge()
            {

                return base.InvokeMethodAsync<System.Int32>(669391297, new object[] {} );
            }
            
            System.Threading.Tasks.Task<Orleans.StorageProvider.RavenDB.TestInterfaces.GenderType> Orleans.StorageProvider.RavenDB.TestInterfaces.IPerson.GetGender()
            {

                return base.InvokeMethodAsync<Orleans.StorageProvider.RavenDB.TestInterfaces.GenderType>(-1388702422, new object[] {} );
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.MethodInvokerAttribute("Orleans.StorageProvider.RavenDB.TestInterfaces.Orleans.StorageProvider.RavenDB.Te" +
        "stInterfaces.IPerson", 438111581)]
    internal class PersonMethodInvoker : global::Orleans.CodeGeneration.IGrainMethodInvoker
    {
        
        int global::Orleans.CodeGeneration.IGrainMethodInvoker.InterfaceId
        {
            get
            {
                return 438111581;
            }
        }
        
        global::System.Threading.Tasks.Task<object> global::Orleans.CodeGeneration.IGrainMethodInvoker.Invoke(global::Orleans.Runtime.IAddressable grain, int interfaceId, int methodId, object[] arguments)
        {

            try
            {{                    if (grain == null) throw new System.ArgumentNullException("grain");
                switch (interfaceId)
                {
                    case 438111581:  // IPerson
                        switch (methodId)
                        {
                            case -1862634097: 
                                return ((IPerson)grain).SetPersonalAttributes((PersonalAttributes)arguments[0]).ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)null; });
                            case 513673718: 
                                return ((IPerson)grain).GetFirstName().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 160660420: 
                                return ((IPerson)grain).GetLastName().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case 669391297: 
                                return ((IPerson)grain).GetAge().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            case -1388702422: 
                                return ((IPerson)grain).GetGender().ContinueWith(t => {if (t.Status == System.Threading.Tasks.TaskStatus.Faulted) throw t.Exception; return (object)t.Result; });
                            default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                        }
                    default:
                        throw new System.InvalidCastException("interfaceId="+interfaceId);
                }
            }}
            catch(Exception ex)
            {{
                var t = new System.Threading.Tasks.TaskCompletionSource<object>();
                t.SetException(ex);
                return t.Task;
            }}
        }
        
        public static string GetMethodName(int interfaceId, int methodId)
        {

            switch (interfaceId)
            {
                
                case 438111581:  // IPerson
                    switch (methodId)
                    {
                        case -1862634097:
                            return "SetPersonalAttributes";
                    case 513673718:
                            return "GetFirstName";
                    case 160660420:
                            return "GetLastName";
                    case 669391297:
                            return "GetAge";
                    case -1388702422:
                            return "GetGender";
                    
                        default: 
                            throw new NotImplementedException("interfaceId="+interfaceId+",methodId="+methodId);
                    }

                default:
                    throw new System.InvalidCastException("interfaceId="+interfaceId);
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Orleans-CodeGenerator", "1.0.970.29197")]
    [System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverageAttribute()]
    [global::Orleans.CodeGeneration.RegisterSerializerAttribute()]
    internal class Orleans_StorageProvider_RavenDB_TestInterfaces_PersonalAttributesSerialization
    {
        
        static Orleans_StorageProvider_RavenDB_TestInterfaces_PersonalAttributesSerialization()
        {
            Register();
        }
        
        public static object DeepCopier(object original)
        {
            Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes input = ((Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes)(original));
            Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes result = new Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes();
            Orleans.Serialization.SerializationContext.Current.RecordObject(original, result);
            result.Age = input.Age;
            result.FirstName = input.FirstName;
            result.Gender = input.Gender;
            result.LastName = input.LastName;
            return result;
        }
        
        public static void Serializer(object untypedInput, Orleans.Serialization.BinaryTokenStreamWriter stream, System.Type expected)
        {
            Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes input = ((Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes)(untypedInput));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Age, stream, typeof(Int32));
            Orleans.Serialization.SerializationManager.SerializeInner(input.FirstName, stream, typeof(String));
            Orleans.Serialization.SerializationManager.SerializeInner(input.Gender, stream, typeof(GenderType));
            Orleans.Serialization.SerializationManager.SerializeInner(input.LastName, stream, typeof(String));
        }
        
        public static object Deserializer(System.Type expected, global::Orleans.Serialization.BinaryTokenStreamReader stream)
        {
            Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes result = new Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes();
            result.Age = ((Int32)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(Int32), stream)));
            result.FirstName = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            result.Gender = ((GenderType)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(GenderType), stream)));
            result.LastName = ((String)(Orleans.Serialization.SerializationManager.DeserializeInner(typeof(String), stream)));
            return result;
        }
        
        public static void Register()
        {
            global::Orleans.Serialization.SerializationManager.Register(typeof(Orleans.StorageProvider.RavenDB.TestInterfaces.PersonalAttributes), DeepCopier, Serializer, Deserializer);
        }
    }
}
#pragma warning restore 162
#pragma warning restore 219
#pragma warning restore 693
#pragma warning restore 1591
#pragma warning restore 1998
#endif
